pkgname=vroxy
pkgver=${PKGVER:-autogenerated}
pkgrel=${PKGREL:-1}
pkgdesc="A simple storage for project builds with REST HTTP API"
arch=("any")
license=('MIT')
url="http://github.com/projects/ZP/repos/vroxy"
groups=()
makedepends=('go' 'make')
provides=()
replaces=()
options=(emptydirs)
source=()
md5sums=()

pkgver() {
    cd $startdir
    make version
}

build() {
    cd $startdir
    echo "Preparing build"
    make all
}

package() {
    PKG_SYSTEMD="${pkgdir}/usr/lib/systemd/system"

    install -Dm 0755 "${startdir}/.out/${pkgname}" "${pkgdir}/usr/bin/${pkgname}"
    install -Dm 0644 "${startdir}/systemd/${pkgname}.service" "$PKG_SYSTEMD/${pkgname}.service"
}
